import { ProductItemInterface } from "@/Types/EcommerceType";

export const ProductApiData: ProductItemInterface[] = [
  {
    id: 1,
    image: "01.jpg",
    name: "Woman T-shirt",
    note: "Regular Flare Fit Women's white Top",
    description: "Rock Paper Scissors Women Tank Top High Neck Cotton Top Stylish Women Top..",
    discountPrice: "35.00",
    price: 50.0,
    status: "none",
    stock: "In stock",
    review: "(250 review)",
    rating: 5,
    category: "Woman",
    colors: ["purple", "pink", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Hudson", "Lee"],
    variants: [
      {
        color: "White",
        images: "01.jpg",
      },
      {
        color: "gray",
        images: "04.jpg",
      },
      {
        color: "gray",
        images: "02.jpg",
      },
      {
        color: "gray",
        images: "03.jpg",
      },
    ],
  },
  {
    id: 2,
    image: "04.jpg",
    name: "Men's Shirt",
    note: "Cotton Regular Fit Men's Shirt",
    description: "Glamcci Men's Cotton Blend Printed One Piece Party Jacket",
    discountPrice: "35.00",
    price: 26.0,
    status: "none",
    stock: "In stock",
    review: "(250 review)",
    rating: 4.5,
    category: "Man",
    colors: ["purple", "pink", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Hudson", "Lee"],
    variants: [
      {
        color: "White",
        images: "01.jpg",
      },
      {
        color: "gray",
        images: "04.jpg",
      },
      {
        color: "gray",
        images: "02.jpg",
      },
      {
        color: "gray",
        images: "03.jpg",
      },
    ],
  },
  {
    id: 3,
    image: "16.jpg",
    name: "Dream Beauty Fashion",
    note: "Tops for Women Stylish",
    description: "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo.",
    discountPrice: "360.00",
    price: 30.0,
    status: "none",
    stock: "In stock",
    review: "(250 review)",
    rating: 4,
    category: "Woman",
    colors: ["White", "pink", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Diesel", "Hudson", "Lee"],
    variants: [
      {
        color: "White",
        images: "01.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
      {
        color: "blue",
        images: "02.jpg",
      },
      {
        color: "gray",
        images: "03.jpg",
      },
    ],
  },
  {
    id: 4,
    image: "07.jpg",
    name: "Men's Jacket",
    note: "Black Full Sleeve Man Jacket",
    description: "Lorate Solid Men's Fashion Full Sleeves Latest Jacket for Men With Button Closure Long Sleeve Casual Torn Lycra Men Denim Shirt.",
    discountPrice: "35.00",
    price: 30.0,
    status: "none",
    stock: "In stock",
    review: "(250 review)",
    rating: 5,
    category: "Man",
    colors: ["White", "pink", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Diesel", "Hudson", "Lee"],
    variants: [
      {
        color: "White",
        images: "01.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
      {
        color: "blue",
        images: "02.jpg",
      },
      {
        color: "purple",
        images: "03.jpg",
      },
    ],
  },
  {
    id: 5,
    image: "02.jpg",
    name: "Men's Shirt",
    note: "Cotton Blend Men's Blue Jacket",
    description: "Lorate Solid Men's Fashion Full Sleeves Latest Jacket for Men With Button Closure Long Sleeve Casual Torn Lycra Denim Jacket.",
    discountPrice: "50.00",
    price: 45.0,
    status: "none",
    stock: "In stock",
    review: "(250 review)",
    rating: 4,
    category: "Man",
    colors: ["White", "pink", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Diesel", "Hudson", "Lee"],
    variants: [
      {
        color: "White",
        images: "01.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
      {
        color: "blue",
        images: "02.jpg",
      },
      {
        color: "black",
        images: "03.jpg",
      },
    ],
  },
  {
    id: 6,
    image: "07.jpg",
    name: "Men's Jacket",
    note: "Black Full Sleeve Man Jacket",
    description: "Lorate Solid Men's Fashion Full Sleeves Latest Jacket for Men With Button Closure Long Sleeve Casual Torn Lycra Men Denim Shirt.",
    discountPrice: "30.00",
    price: 35.0,
    status: "none",
    stock: "Out of stock",
    review: "(250 review)",
    rating: 4.5,
    category: "Man",
    colors: ["black", "pink", "yellow"],
    size: ["M", "L", "XL"],
    tags: ["Hudson"],
    variants: [
      {
        color: "black",
        images: "01.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
      {
        color: "yellow",
        images: "02.jpg",
      },
      {
        color: "blue",
        images: "02.jpg",
      },
    ],
  },
  {
    id: 7,
    image: "06.jpg",
    name: "Woman T-shirt",
    note: "Solid Denim Jacket",
    description: "Rock Paper Scissors Womens Tank Top High Neck Cotton Top Stylish Women Top..",
    discountPrice: "30.00",
    price: 25.0,
    status: "none",
    stock: "Out of stock",
    review: "(250 review)",
    rating: 4,
    category: "Woman",
    colors: ["black", "pink", "yellow"],
    size: ["M", "L", "XL"],
    tags: ["Lee"],
    variants: [
      {
        color: "black",
        images: "01.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
      {
        color: "yellow",
        images: "02.jpg",
      },
      {
        color: "red",
        images: "02.jpg",
      },
    ],
  },
  {
    id: 8,
    image: "03.jpg",
    name: "Woman T-shirt",
    note: "Cotton Blend Women's Coat",
    description: "Women's Classic Stretchy All Time Trendy Pleated Skirt Western coat midi Skirt plited Lehenga.",
    discountPrice: "480.00",
    price: 426.0,
    status: "none",
    stock: "Out of stock",
    review: "(250 review)",
    rating: 5,
    category: "Woman",
    colors: ["black", "pink", "yellow"],
    size: ["M", "L", "XL"],
    tags: ["Diesel", "Hudson", "Lee"],
    variants: [
      {
        color: "black",
        images: "01.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
      {
        color: "yellow",
        images: "02.jpg",
      },
      {
        color: "purple",
        images: "02.jpg",
      },
    ],
  },
  {
    id: 9,
    image: "10.jpg",
    name: "Men's Jacket",
    note: "Men's Full Black Suit",
    description: "Attitude is everything Cotton Men's Black Suit.",
    discountPrice: "55.00",
    price: 50.0,
    status: "none",
    stock: "Out of stock",
    review: "(250 review)",
    rating: 4.5,
    category: "Man",
    colors: ["gray", "pink", "yellow"],
    size: ["M", "L", "XL"],
    tags: ["Lee", "Spykar"],
    variants: [
      {
        color: "gray",
        images: "01.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
      {
        color: "yellow",
        images: "02.jpg",
      },
      {
        color: "blue",
        images: "03.jpg",
      },
    ],
  },
  {
    id: 10,
    image: "14.jpg",
    name: "Men's Shirt",
    note: "Men's Denim T-shirt",
    description: "Lorate Solid Men's Fashion Full Sleeves Latest Jacket for Men With Button Closure Long Sleeve Casual Torn Lycra Denim Shirt.",
    discountPrice: "70.00",
    price: 60.0,
    status: "none",
    stock: "Out of stock",
    review: "(250 review)",
    rating: 5,
    category: "Man",
    colors: ["black", "pink", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Lee", "Denizen"],
    variants: [
      {
        color: "black",
        images: "01.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
      {
        color: "blue",
        images: "02.jpg",
      },
      {
        color: "yellow",
        images: "03.jpg",
      },
    ],
  },
  {
    id: 11,
    image: "15.jpg",
    name: "Dream Beauty Fashion",
    note: "Stylish Party Wear for women",
    description: "Stylish Party Wear for women",
    discountPrice: "350.00",
    price: 30.0,
    status: "Hot",
    ribbonClassName: "ribbon ribbon-clip ribbon-warning",
    stock: "In stock",
    review: "(250 review)",
    rating: 4,
    category: "Woman",
    colors: ["black", "pink", "red"],
    size: ["M", "L", "XL"],
    tags: ["Diesel", "Spykar"],
    variants: [
      {
        color: "black",
        images: "01.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
      {
        color: "red",
        images: "02.jpg",
      },
      {
        color: "yellow",
        images: "03.jpg",
      },
    ],
  },
  {
    id: 12,
    image: "07.jpg",
    name: "Men's Jacket",
    note: "Denim Regular Men's Jacket",
    description: "Lorate Solid Men's Fashion Full Sleeves Latest Jacket for Men With Button Closure Long Sleeve Casual Torn Lycra Men Denim Shirt.",
    discountPrice: "35.00",
    price: 30.0,
    status: "none",
    stock: "In stock",
    review: "(250 review)",
    rating: 5,
    category: "Man",
    colors: ["black", "pink", "red", "gray"],
    size: ["M", "L", "XL"],
    tags: ["Levi's", "Diesel"],
    variants: [
      {
        color: "black",
        images: "01.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
      {
        color: "red",
        images: "02.jpg",
      },
      {
        color: "gray",
        images: "03.jpg",
      },
    ],
  },
  {
    id: 13,
    image: "09.jpg",
    name: "Woman T-shirt",
    note: "Regular Flare Fit Women's white Top",
    description: "Rock Paper Scissors Women Tank Top High Neck Cotton Top Stylish Women Top..",
    discountPrice: "50.00",
    price: 45.0,
    status: "none",
    stock: "In stock",
    review: "(250 review)",
    rating: 5,
    category: "Woman",
    colors: ["black", "pink", "red", "gray"],
    size: ["M", "L", "XL"],
    tags: ["Diesel", "Spykar", "Lee"],
    variants: [
      {
        color: "black",
        images: "01.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
      {
        color: "red",
        images: "02.jpg",
      },
      {
        color: "gray",
        images: "03.jpg",
      },
    ],
  },
  {
    id: 14,
    image: "07.jpg",
    name: "Men's Jacket",
    note: "Denim Regular Men's Jacket",
    description: "Lorate Solid Men's Fashion Full Sleeves Latest Jacket for Men With Button Closure Long Sleeve Casual Torn Lycra Men Denim Shirt.",
    discountPrice: "35.00",
    price: 30.0,
    status: "none",
    stock: "In stock",
    review: "(250 review)",
    rating: 5,
    category: "Man",
    colors: ["black", "pink", "red", "gray"],
    size: ["M", "L", "XL"],
    tags: ["Levi's", "Lee"],
    variants: [
      {
        color: "black",
        images: "01.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
      {
        color: "red",
        images: "02.jpg",
      },
      {
        color: "gray",
        images: "03.jpg",
      },
    ],
  },
  {
    id: 15,
    image: "14.jpg",
    name: "Men's Shirt",
    note: "Men's Denim T-shirt",
    description: "Lorate Solid Men's Fashion Full Sleeves Latest Jacket for Men With Button Closure Long Sleeve Casual Torn Lycra Denim Shirt.",
    discountPrice: "70.00",
    price: 60.0,
    status: "none",
    stock: "Out of stock",
    review: "(250 review)",
    rating: 4,
    category: "Man",
    colors: ["black", "pink", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Lee"],
    variants: [
      {
        color: "black",
        images: "01.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
      {
        color: "blue",
        images: "02.jpg",
      },
      {
        color: "yellow",
        images: "03.jpg",
      },
    ],
  },
  {
    id: 16,
    image: "16.jpg",
    name: "Dream Beauty Fashion",
    note: "Tops for Women Stylish",
    description: "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo.",
    discountPrice: "360.00",
    price: 30.0,
    status: "none",
    stock: "In stock",
    review: "(250 review)",
    rating: 5,
    category: "Woman",
    colors: ["White", "pink", "blue"],
    size: ["M", "L", "XL"],
    tags: ["Diesel", "Hudson", "Lee"],
    variants: [
      {
        color: "White",
        images: "01.jpg",
      },
      {
        color: "pink",
        images: "04.jpg",
      },
      {
        color: "blue",
        images: "02.jpg",
      },
      {
        color: "gray",
        images: "03.jpg",
      },
    ],
  },
];
